### ISSUE TITLE
要是文字支持自动换行就更好了

### ISSUE THREAD

**Issue by HelenTim** [wgj0913/auto-image-watermark#2]
设置texts里每一段文本的宽度然后设置行高，字体太长时就换行。下面有一段代码可以参考一下：
 function drawText(tetx,left,top,fontSize,fontColor,fontWeight,fontLineHeight,textAlign,stringWidth){
                    // tetx:需要渲染的文本
                    // left：刚开始时当前文本距离canvas左边的距离
                    // top：刚开始时当前文本距离canvas顶部的距离
                    // fontSize：字体大小；
                    // fontColor:字体颜色；
                    // fontWeight：字体粗细
                    // fontLineHeight：字体行高
                    // tetxAlign:字体在水平方向对齐方式
                    // stringWidth：每一段文本的最大宽度
                    // 
                    var decribe = tetx;
                    var initHeight=top;//绘制字体距离canvas顶部初始的高度
                    var lineWidth = 0;
                    var lastSubStrIndex= 0; //每次开始截取的字符串的索引
                    ctx.fillStyle = fontColor;
                    ctx.font = ''+fontWeight+' '+ fontSize + ' ' +'\''+'微软雅黑'+'\'';
                    ctx.textAlign = textAlign || "left";
                    ctx.textAlign.indexOf('center')>-1 && (left += stringWidth/2);
                    for(let i=0;i<decribe.length;i++){
                        lineWidth+=ctx.measureText(decribe[i]).width;
                        if(lineWidth>stringWidth){
                            ctx.fillText(decribe.substring(lastSubStrIndex,i),left,initHeight);//绘制截取部分
                            initHeight+=fontLineHeight;
                            lineWidth=0;
                            lastSubStrIndex=i;
                        }
                        if(i==decribe.length-1){//绘制剩余部分
                            ctx.fillText(decribe.substring(lastSubStrIndex,i+1),left,initHeight);
                        }
                    }
                }

**Comment by MartinDelophy** [comment]
已支持。 texts 参数说明中 新增加 API autoLines 。 换行是 true， 不换行省略号为 false
